// WARNING: Please don't edit this file. It was generated by C++/WinRT v1.0.180227.3

#pragma once
#include "winrt/base.h"

WINRT_WARNING_PUSH

static_assert(winrt::check_version(CPPWINRT_VERSION, "1.0.180227.3"), "Mismatched component and base headers.");
#include "winrt/Windows.Foundation.h"
#include "winrt/Windows.Foundation.Collections.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/Dx11Xaml.2.h"

namespace winrt::impl {

template <typename D>
struct produce<D, Dx11Xaml::IMainPage> : produce_base<D, Dx11Xaml::IMainPage>
{};

}

WINRT_EXPORT namespace winrt::Dx11Xaml {

inline MainPage::MainPage() :
    MainPage(get_activation_factory<MainPage>().ActivateInstance<MainPage>())
{}

}

WINRT_EXPORT namespace std {

template<> struct hash<winrt::Dx11Xaml::IMainPage> : winrt::impl::hash_base<winrt::Dx11Xaml::IMainPage> {};
template<> struct hash<winrt::Dx11Xaml::MainPage> : winrt::impl::hash_base<winrt::Dx11Xaml::MainPage> {};

}

WINRT_WARNING_POP
